version = 1

test_patterns = [
  "**/client/**/*.test.tsx",
  "**/server/tests/**",
  "test_*.py",
  "*.test.tsx"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
  dialect = "typescript"
